development:
  dialect: postgres
  dir: ./docs/schema
  table: migration
  datasource: host=localhost port=5432 dbname=todo user=postgres password=postgres sslmode=disable
test:
  dialect: postgres
  dir: ./docs/schema
  table: migration
  datasource: host=localhost port=54321 dbname=todo user=postgres password=postgres sslmode=disable