version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    container_name: todo-db
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  testdb:
    image: postgres:16
    restart: always
    container_name: todo-testdb
    ports:
      - ${TEST_DB_PORT}:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
